# -*- mode: ruby -*-
# vi: set ft=ruby :

# unless Vagrant.has_plugin?("vagrant-hostsupdater")
#   raise 'some-plugin is not installed!'
# end

# http://matthewcooper.net/2015/01/15/automatically-installing-vagrant-plugin-dependencies/
required_plugins = %w( vagrant-hostsupdater )
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin};vagrant #{ARGV.join(" ")}" unless Vagrant.has_plugin? plugin || ARGV[0] == 'plugin'
end

Vagrant.configure("2") do |config|
 
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.10.100"
  config.hostsupdater.aliases = ["develoment.local"]

end
